/**
 * Build Script — Apex Care Hospital Website
 * 
 * Scans image folders and generates images-manifest.json
 * Run this after adding/removing images, or as Vercel build step.
 * 
 * Folder structure:
 *   images/hero/      → Hero section background images (rotated automatically)
 *   images/gallery/   → Gallery section photos
 *   images/about/     → About section photos
 *   images/logo.png   → Hospital logo
 */

const fs = require('fs');
const path = require('path');

const IMAGES_DIR = path.join(__dirname, 'images');
const OUTPUT_FILE = path.join(__dirname, 'images-manifest.json');

const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.gif', '.svg']);

function scanFolder(folderPath) {
  if (!fs.existsSync(folderPath)) return [];
  
  return fs.readdirSync(folderPath)
    .filter(file => {
      const ext = path.extname(file).toLowerCase();
      return IMAGE_EXTENSIONS.has(ext) && !file.startsWith('.');
    })
    .sort()
    .map(file => {
      const relativePath = path.relative(__dirname, path.join(folderPath, file));
      // Normalize to forward slashes for web URLs
      return relativePath.split(path.sep).join('/');
    });
}

function buildManifest() {
  const manifest = {
    _generated: new Date().toISOString(),
    _instructions: "Auto-generated by build.js — do NOT edit manually. Add images to the folders and run 'npm run build'.",
    logo: null,
    hero: [],
    gallery: [],
    about: []
  };

  // Logo
  const logoFiles = ['logo.png', 'logo.jpg', 'logo.webp', 'logo.svg'];
  for (const logoFile of logoFiles) {
    const logoPath = path.join(IMAGES_DIR, logoFile);
    if (fs.existsSync(logoPath)) {
      manifest.logo = `images/${logoFile}`;
      break;
    }
  }

  // Sections
  manifest.hero = scanFolder(path.join(IMAGES_DIR, 'hero'));
  manifest.gallery = scanFolder(path.join(IMAGES_DIR, 'gallery'));
  manifest.about = scanFolder(path.join(IMAGES_DIR, 'about'));

  // Write manifest JSON
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(manifest, null, 2));

  // Write manifest JS for file:// protocol compatibility
  const JS_OUTPUT_FILE = path.join(__dirname, 'images-manifest.js');
  fs.writeFileSync(JS_OUTPUT_FILE, `window.IMAGES_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`);
  
  console.log('✅ images-manifest.json and images-manifest.js generated successfully!');
  console.log(`   Logo:    ${manifest.logo || '(none)'}`);
  console.log(`   Hero:    ${manifest.hero.length} image(s)`);
  console.log(`   Gallery: ${manifest.gallery.length} image(s)`);
  console.log(`   About:   ${manifest.about.length} image(s)`);
}

buildManifest();
